"""
    GraphWavelet <: ComponentModel

A component model for multiresolution Spectral Graph Wavelet (SGW) spatial fields.
This component models a continuous spatial random effect over an irregular spatial mesh
(e.g., hexagonal grid, marine partitioning, or coastal graph) by placing hierarchical
priors on the multiscale wavelet coefficients in the spectral graph domain.

# Version
v1.0.0

# Mathematical Summary
Classical 2D wavelet models (`WaveletGP`) require regular Cartesian grids of size
``2^N \\times 2^N``. For irregular marine domains with complex coastlines and islands,
the Spectral Graph Wavelet component operates directly on the graph Laplacian:
```math
\\mathbf{L} = \\mathbf{I} - \\mathbf{D}^{-1/2} \\mathbf{W} \\mathbf{D}^{-1/2}
```
The spatial field ``\\mathbf{f} \\in \\mathbb{R}^S`` across ``S`` spatial units is modeled
as a multiresolution expansion over localized wavelet atoms:
```math
\\mathbf{f} = \\mathbf{\\Psi} \\mathbf{w}
```
where ``\\mathbf{\\Psi} \\in \\mathbb{R}^{S \\times K}`` is the precomputed multiresolution
graph wavelet dictionary generated by `graph_wavelet_basis_matrix(W; num_scales=J)`.
The dictionary consists of:
1. Macro-scale baseline scaling atoms:
   ``\\boldsymbol{\\phi}_k = h(\\mathbf{L}) \\boldsymbol{\\delta}_k``
2. Multiscale detail wavelet atoms across ``J`` dilated scales:
   ``\\boldsymbol{\\psi}_{j, k} = g(s_j \\mathbf{L}) \\boldsymbol{\\delta}_k``

The wavelet coefficients ``\\mathbf{w}`` are given independent zero-mean normal priors
whose variances decay across frequency scales according to a power law:
```math
w_k \\sim \\mathcal{N}(0, \\sigma^2(k))
```
```math
\\sigma^2(k) = \\sigma_0^2 \\cdot 2^{-\\alpha \\cdot \\text{scale\\_level}(k)}
```
where:
- ``\\sigma_0``: Overall spatial standard deviation of the wavelet field.
- ``\\alpha``: Smoothness decay rate across frequency scales. Higher ``\\alpha > 0``
  penalizes fine-scale spatial roughness (favoring smooth regional trends), while
  ``\\alpha \\to 0`` allows rich localized spatial micro-features.

# Inputs
- **Required**:
  - A spatial index variable (e.g., `s_idx`, `hex_id`) passed to `random()`.
  - An adjacency matrix `W` passed as a keyword argument to `@bstm(..., W=W)`.
- **Optional (in `random()` call)**:
  - `num_scales`: `Int`, number of detail scales ``J`` (default: `4`).
  - `order`: `Int`, Chebyshev polynomial degree ``M`` (default: `25`).
  - `anchors`: `Union{Symbol, Vector{Int}}`, anchor nodes or `:all` (default: `:all`).
  - `sigma0`: `Distribution`, prior for overall scale (default: `Exponential(1.0)`).
  - `alpha`: `Distribution`, prior for smoothness decay (default: `Exponential(1.0)`).
  - `method`: `Symbol`, computational parameterization (`:noncentered` or `:centered`,
    default: `:noncentered`).

# Outputs (Parameter Names)
- `sigma0_<key>`: Overall spatial scale parameter.
- `alpha_<key>`: Smoothness decay parameter across frequency bands.
- `ure_<key>`: Standard normal innovations for wavelet coefficients (for `:noncentered`).
- `sre_<key>`: Structured spatial effect vector.

# Key References
- Hammond, D. K., Vandergheynst, P., & Gribonval, R. (2011). Wavelets on graphs via
  spectral graph theory. Applied and Computational Harmonic Analysis, 30(2), 129-150.
- Shuman, D. I., Narang, S. K., Frossard, P., Ortega, A., & Vandergheynst, P. (2013).
  The emerging field of signal processing on graphs. IEEE Signal Processing Magazine.
"""
struct GraphWavelet <: ComponentModel
    sigma0::Distribution
    alpha::Distribution
    num_scales::Int
    order::Int
    anchors::Union{Symbol, Vector{Int}}
    method::Symbol
end

COMPONENT_TYPE_REGISTRY[:graph_wavelet] = GraphWavelet
COMPONENT_TYPE_REGISTRY[:sgw] = GraphWavelet

COMPONENT_CONSTRUCTORS[:graph_wavelet] = (p, params) -> GraphWavelet(
    get(p, :sigma0, get(p, :sigma, Exponential(1.0))),
    get(p, :alpha, Exponential(1.0)),
    get(params, :num_scales, 4),
    get(params, :order, 25),
    get(params, :anchors, :all),
    get(params, :method, :noncentered)
)
COMPONENT_CONSTRUCTORS[:sgw] = COMPONENT_CONSTRUCTORS[:graph_wavelet]

MODEL_TO_STRUCTURE_MAP[:graph_wavelet] = :spatial
MODEL_TO_STRUCTURE_MAP[:sgw] = :spatial

"""
    get_precomputes(m::GraphWavelet, M::NamedTuple, mod_data::Dict)::NamedTuple

Precomputes the multiresolution graph wavelet basis matrix and scale frequency indices.
"""
function get_precomputes(m::GraphWavelet, M::NamedTuple, mod_data::Dict)::NamedTuple
    if !hasproperty(M, :W) || !isa(M.W, AbstractMatrix) || isempty(M.W)
        error(
            "GraphWavelet component '$(mod_data[:key])' requires an adjacency matrix `W` " *
            "passed to `@bstm(..., W=W)`."
        )
    end

    W = M.W
    s_N = size(W, 1)

    # Resolve spatial observation mapping
    s_idx = if hasproperty(M, :s_idx)
        Vector{Int}(M.s_idx)
    else
        vars = mod_data[:variables]
        if !isempty(vars) && hasproperty(M.data, Symbol(vars[1]))
            Vector{Int}(M.data[!, Symbol(vars[1])])
        else
            error(
                "GraphWavelet component '$(mod_data[:key])' requires a spatial index variable."
            )
        end
    end

    # Precompute multiresolution dictionary Ψ (size S × K)
    Psi = graph_wavelet_basis_matrix(
        W;
        num_scales = m.num_scales,
        order = m.order,
        anchor_indices = m.anchors,
        normalized = true
    )

    n_anchors = m.anchors === :all ? s_N : length(m.anchors)
    total_cols = size(Psi, 2)

    # Construct frequency decay index vector
    # Macro baseline (columns 1..n_anchors): scale level 0 (decay power 0.0)
    # Detail scales j = 1..num_scales:
    # Scale s_j where j=1 is fine (high frequency) and j=num_scales is coarse (low frequency).
    # Power is (num_scales - j + 1), so highest frequency decays most with alpha.
    scale_indices = zeros(Float64, total_cols)
    col = 1
    for a in 1:n_anchors
        scale_indices[col] = 0.0
        col += 1
    end
    for j in 1:m.num_scales
        decay_power = Float64(m.num_scales - j + 1)
        for a in 1:n_anchors
            scale_indices[col] = decay_power
            col += 1
        end
    end

    return (
        Psi = Psi,
        scale_indices = scale_indices,
        n_latent = total_cols,
        s_N = s_N,
        s_idx = s_idx,
        num_scales = m.num_scales
    )
end

"""
    get_priors(m::GraphWavelet, spec::NamedTuple, arch::String, outcome_idx, M)::String

Generates Turing code for the GraphWavelet scale hyperparameters and wavelet innovations.
"""
function get_priors(
    m::GraphWavelet, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing},
    M::NamedTuple
)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    key = spec.key
    priors = String[]

    push!(priors, "$(p_names.sigma0) ~ $(_distribution_to_string(m.sigma0))")
    push!(priors, "$(p_names.alpha) ~ $(_distribution_to_string(m.alpha))")

    n_latent = spec.hyper.n_latent
    if m.method == :noncentered
        push!(
            priors,
            "$(p_names.ure) ~ MvNormal(zeros(T, $(n_latent)), I)"
        )
    else
        push!(
            priors,
            "$(p_names.sre) ~ MvNormal(zeros(T, $(n_latent)), I)"
        )
    end

    return join(priors, "\n    ")
end

"""
    get_updates(m::GraphWavelet, spec::NamedTuple, arch::String, outcome_idx, M)::String

Generates Turing code for synthesizing the multiscale spatial field and updating `eta`.
"""
function get_updates(
    m::GraphWavelet, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing},
    M::NamedTuple
)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    eta_target = (arch == "multivariate") ? "eta_latent[:, $(outcome_idx)]" : "eta"
    key = spec.key

    return """
    # --- GraphWavelet Component: $(key) ---
    let
        hyper = spec_registry[:$(key)].hyper
        Psi = hyper.Psi
        scale_indices = hyper.scale_indices
        
        scale_variances = $(p_names.sigma0)^2 .* (2.0 .^ (-$(p_names.alpha) .* scale_indices))
        wavelet_coeffs = $(p_names.ure) .* sqrt.(scale_variances)
        latent_field = Psi * wavelet_coeffs
        $(p_names.sre) = latent_field
        $(eta_target) = $(eta_target) .+ view(latent_field, M.s_idx)
    end
    """
end

"""
    get_effects(m::GraphWavelet, chain, spec::NamedTuple, M::NamedTuple, PS)::NamedTuple

Reconstructs the multiscale graph wavelet spatial field from posterior MCMC samples.
"""
function get_effects(
    m::GraphWavelet, chain, spec::NamedTuple, M::NamedTuple,
    PS::Union{NamedTuple, Nothing}
)::NamedTuple
    n_samples = _get_chain_n_samples(chain)
    outcomes_N = M.outcomes_N
    is_multivariate_model = M.model_arch == "multivariate"
    p_names = string.(keys(chain))

    structured_effects = Vector{Matrix{Float64}}()

    hyper = spec.hyper
    Psi = hyper.Psi
    scale_indices = hyper.scale_indices
    n_latent = hyper.n_latent

    # Training and prediction spatial indices
    s_idx_train = hyper.s_idx
    s_idx_full = if !isnothing(PS) && hasproperty(PS.data, Symbol(spec.var))
        vcat(s_idx_train, Int.(PS.data[!, Symbol(spec.var)]))
    elseif !isnothing(PS) && hasproperty(PS, :s_idx)
        vcat(s_idx_train, Int.(PS.s_idx))
    else
        s_idx_train
    end
    N_total = length(s_idx_full)

    for k in 1:outcomes_N
        p_names_k = generate_full_variable_names(spec, M.model_arch, k)
        sigma0_name = _find_parameter(
            p_names, string(p_names_k.sigma0), k, is_multivariate_model
        )
        alpha_name = _find_parameter(
            p_names, string(p_names_k.alpha), k, is_multivariate_model
        )
        ure_name = _find_parameter(
            p_names, string(p_names_k.ure), k, is_multivariate_model
        )

        if isempty(sigma0_name) || isempty(alpha_name) || isempty(ure_name)
            @warn(
                "Parameters for GraphWavelet component $(spec.key) (outcome $k) not found. " *
                "Returning zero-matrix."
            )
            push!(structured_effects, zeros(Float64, N_total, n_samples))
            continue
        end

        sigma0_samples = get_params_vector(chain, sigma0_name, 1)[:, 1]
        alpha_samples = get_params_vector(chain, alpha_name, 1)[:, 1]
        ure_samples = get_params_matrix(chain, ure_name, n_latent)

        effect_k = zeros(Float64, N_total, n_samples)
        for s in 1:n_samples
            sig0 = sigma0_samples[s]
            alph = alpha_samples[s]
            innov = ure_samples[s, :]

            scale_variances = sig0^2 .* (2.0 .^ (-alph .* scale_indices))
            w = innov .* sqrt.(scale_variances)
            latent_s = Psi * w
            effect_k[:, s] = latent_s[s_idx_full]
        end
        push!(structured_effects, effect_k)
    end

    return (structured = structured_effects, noisy = structured_effects)
end
