"""
    ShotNoiseCoxProcess <: ComponentModel

A component model for a Shot-Noise Cox Process, used for modeling spatial point
patterns. The intensity surface is generated by placing a number of "parent" points
(the "shots") in the domain, each contributing a kernel-based bump to the overall
intensity.

# Version
v1.0.1 (2026-08-10)

# Mathematical Summary
A Shot-Noise Cox process models point counts \$y_j\$ in an areal unit \$A_j\$ by assuming
they follow a Poisson distribution whose rate is the integral of a latent intensity
surface \$\\lambda(s)\$ over that area.
\$y_j \\sim \\text{Poisson}\\left( \\int_{A_j} \\lambda(s) ds \\right)\$

The intensity surface \$\\lambda(s)\$ is constructed as the sum of kernel functions
centered at \$N\$ parent points (the "shots"):
\$\\lambda(s) = \\exp(\\eta_s) \\sum_{i=1}^{N} A_i k(s, c_i; \\ell)\$
where:
- \$\\eta_s\$ is the contribution from other model components (intercept, fixed effects).
- \$c_i\$ are the locations of the parent points, typically sampled from a uniform
  distribution over the domain.
- \$A_i\$ is the amplitude (height) of the i-th shot.
- \$k(\\cdot)\$ is a kernel function (e.g., squared exponential) with lengthscale \$\\ell\$.
- The number of parents, \$N\$, can be fixed or a random variable.

# Assumptions
- The point process intensity can be represented as a sum of localized kernel effects.
- The observation data `y` represents counts aggregated over discrete areal units.

# Best Use Case
Modeling clustered point patterns where the clusters themselves are randomly located.
Examples include modeling the locations of trees in a forest, epicenters of
earthquakes, or cases of a communicable disease.

# Key References
- Møller, J., Syversveen, A. R., & Waagepetersen, R. P. (1998). *Log Gaussian
  Cox Processes*. Scandinavian Journal of Statistics, 25(3), 451-482.
- Wikipedia: Cox process

# Fields
- `n_parents::Union{Int, UnivariateDistribution}`: The number of parent points. Can be
  fixed or a random variable with a prior.
- `kernel::String`: The name of the kernel function for each shot (e.g., "se").
- `lengthscale::Distribution`: The prior for the kernel lengthscale.
- `amplitude::Distribution`: The prior for the amplitude (height) of each shot.
- `method::Symbol`: The computational method. Can be `:direct` (default) or `:grid`.
- `grid_resolution::Int`: The resolution of the grid for the `:grid` method.
"""
struct ShotNoiseCoxProcess <: ComponentModel
    n_parents::Union{Int, UnivariateDistribution}
    kernel::String
    lengthscale::Distribution
    amplitude::Distribution
    method::Symbol
    grid_resolution::Int
end

COMPONENT_TYPE_REGISTRY[:shotnoisecoxprocess] = ShotNoiseCoxProcess

COMPONENT_CONSTRUCTORS[:shotnoisecoxprocess] = (p, params) -> ShotNoiseCoxProcess(
    get(params, :n_parents, 50),
    string(get(params, :kernel, "se")),
    p.lengthscale,
    p.amplitude,
    get(params, :method, :direct),
    get(params, :grid_resolution, 100)
)

MODEL_TO_STRUCTURE_MAP[:shotnoisecoxprocess] = :spatial

"""
    get_datastructures!(m_type::Type{<:ShotNoiseCoxProcess}, M::Dict, mod_data::Dict)

Performs data-dependent setup for the `ShotNoiseCoxProcess`. It ensures that spatial
coordinates are available to define the domain and that grid areas are processed.
It assumes a point process where observations `y` correspond to counts in areal units.
"""
function get_datastructures!(
    m_type::Type{<:ShotNoiseCoxProcess}, M::Dict, mod_data::Dict
)::Bool
    params = mod_data[:params]
    data = M[:data]

    if !hasproperty(data, :s_x) || !hasproperty(data, :s_y)
        error(
            "ShotNoiseCoxProcess requires continuous spatial coordinates `s_x` and " *
            "`s_y` to define the domain."
        )
    end

    if !haskey(M, :s_N)
        if haskey(M, :s_idx)
            M[:s_N] = length(unique(M[:s_idx]))
        else
            M[:s_N] = nrow(data)
            M[:s_idx] = 1:M[:s_N]
            @warn "Spatial index `s_idx` not found. Assuming one observation per " *
                  "unique location, ordered as in the data."
        end
    end

    if !haskey(M, :centroids)
        coord_map = Dict{Int, Point2D}()
        for i in 1:nrow(data)
            idx = M[:s_idx][i]
            if !haskey(coord_map, idx)
                coord_map[idx] = Point2D(data.s_x[i], data.s_y[i])
            end
        end
        if length(coord_map) < M[:s_N]
            error("Could not resolve unique coordinates for all $(M[:s_N]) spatial units.")
        end
        M[:centroids] = [coord_map[i] for i in 1:M[:s_N]]
    end

    if haskey(params, :grid_areas)
        ga_val = params[:grid_areas]
        if ga_val isa Symbol && hasproperty(data, ga_val)
            M[:grid_areas] = data[!, ga_val]
        elseif ga_val isa AbstractVector
            M[:grid_areas] = ga_val
        else
            calling_mod = get(M, :calling_module, Main)
            try; M[:grid_areas] = Core.eval(calling_mod, ga_val);
            catch; @warn "Could not resolve grid_areas. Defaulting to unit areas."; M[:grid_areas] = ones(M[:s_N]); end
        end
    else
        @warn "ShotNoiseCoxProcess specified, but `grid_areas` is missing. Defaulting to unit areas."
        M[:grid_areas] = ones(M[:s_N])
    end

    if M[:y_obs] isa AbstractMatrix
        if size(M[:y_obs], 2) > 1
            error("ShotNoiseCoxProcess only supports a single outcome variable.")
        end
        M[:y_obs] = vec(M[:y_obs])
    end
    if length(M[:y_obs]) != M[:s_N]
        @warn "Length of y_obs ($(length(M[:y_obs]))) does not match number of spatial units s_N ($(M[:s_N])). Ensure data is aggregated to one count per spatial unit."
    end

    return true
end


"""
    get_precomputes(m::ShotNoiseCoxProcess, M::NamedTuple, mod_data::Dict)::NamedTuple

Performs pre-calculations for the `ShotNoiseCoxProcess`. It determines the spatial
domain bounds and, if using the `:grid` method, pre-computes the fine grid and
interpolation weights for each observation location.
"""
function get_precomputes(
    m::ShotNoiseCoxProcess, M::NamedTuple, mod_data::Dict
)::NamedTuple
    coords = M.data[!, [:s_x, :s_y]]
    x_min, x_max = extrema(coords.s_x)
    y_min, y_max = extrema(coords.s_y)
    
    domain_bounds = (x_min=x_min, x_max=x_max, y_min=y_min, y_max=y_max)
    
    precomputes = Dict{Symbol, Any}(
        :domain_bounds => domain_bounds,
        :obs_locs => M.centroids,
        :grid_areas => M.grid_areas
    )

    if m.method == :grid
        res = m.grid_resolution
        grid_x = range(x_min, x_max, length=res)
        grid_y = range(y_min, y_max, length=res)
        
        interpolation_data = []
        for obs_loc in M.centroids
            ix = searchsortedlast(grid_x, obs_loc.x)
            iy = searchsortedlast(grid_y, obs_loc.y)
            ix = max(1, min(ix, res - 1))
            iy = max(1, min(iy, res - 1))
            
            dx = (obs_loc.x - grid_x[ix]) / (grid_x[ix+1] - grid_x[ix])
            dy = (obs_loc.y - grid_y[iy]) / (grid_y[iy+1] - grid_y[iy])
            
            push!(interpolation_data, (ix=ix, iy=iy, dx=dx, dy=dy))
        end
        precomputes[:fine_grid_x] = grid_x
        precomputes[:fine_grid_y] = grid_y
        precomputes[:interpolation_data] = interpolation_data
    end

    return NamedTuple(precomputes)
end


"""
    get_priors(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx, M)

Generates the Turing code for the `ShotNoiseCoxProcess` component's priors.
"""
function get_priors(
    m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String,
    outcome_idx::Union{Int, Nothing}, M::NamedTuple
)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    bounds = spec.precomputes.domain_bounds

    priors = String[]

    n_parents_str = if m.n_parents isa UnivariateDistribution
        push!(priors, "$(p_names.latent) ~ $(_distribution_to_string(m.n_parents))")
        string(p_names.latent)
    else
        string(m.n_parents)
    end

    push!(priors, "$(p_names.raw)_parent_locs_x ~ filldist(Uniform($(bounds.x_min), $(bounds.x_max)), $(n_parents_str))")
    push!(priors, "$(p_names.raw)_parent_locs_y ~ filldist(Uniform($(bounds.y_min), $(bounds.y_max)), $(n_parents_str))")
    push!(priors, "$(p_names.ls) ~ $(_distribution_to_string(m.lengthscale))")
    push!(priors, "$(p_names.amplitude) ~ filldist($(_distribution_to_string(m.amplitude)), $(n_parents_str))")
    
    return join(priors, "\n    ")
end



"""
    get_updates(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx, M)

Generates the Turing code to construct the `ShotNoiseCoxProcess` intensity surface
and its custom Poisson likelihood. This component overrides the standard likelihood.
It supports two methods: `:direct` and `:grid`.
"""
function get_updates(
    m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String,
    outcome_idx::Union{Int, Nothing}, M::NamedTuple
)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    
    n_parents_str = if m.n_parents isa UnivariateDistribution
        string(p_names.latent)
    else
        string(m.n_parents)
    end

    likelihood_code = """
        local grid_areas = spec_registry[:$(spec.key)].precomputes.grid_areas
        for s in 1:M.s_N
            local y_s = M.y_obs[s] 
            local A_s = grid_areas[s]
            local lambda_s = intensity_at_obs[s] * A_s
            
            # Add base contribution from other model components to the log-intensity
            lambda_s *= exp(eta[s])

            Turing.@addlogprob! (y_s * log(lambda_s + 1e-9) - lambda_s)
        end
        M[:likelihood_handled] = true # Signal to assembler that likelihood is handled
    """

    direct_code = """
        # --- ShotNoiseCoxProcess Model (Direct): $(spec.key) ---
        let
            local obs_locs = spec_registry[:$(spec.key)].precomputes.obs_locs
            local parent_locs = hcat($(p_names.raw)_parent_locs_x, $(p_names.raw)_parent_locs_y)
            
            local intensity_at_obs = zeros(T, M.s_N)
            for i in 1:M.s_N
                local intensity_i = 0.0
                for j in 1:$(n_parents_str)
                    local dist_sq = (obs_locs[i].x - parent_locs[j, 1])^2 + (obs_locs[i].y - parent_locs[j, 2])^2
                    local kernel_val = exp(-0.5 * dist_sq / ($(p_names.ls)^2))
                    intensity_i += $(p_names.amplitude)[j] * kernel_val
                end
                intensity_at_obs[i] = intensity_i
            end
            $(likelihood_code)
        end
    """

    grid_code = """
        # --- ShotNoiseCoxProcess Model (Grid): $(spec.key) ---
        let
            local grid_x = spec_registry[:$(spec.key)].precomputes.fine_grid_x
            local grid_y = spec_registry[:$(spec.key)].precomputes.fine_grid_y
            local res = $(m.grid_resolution)
            local parent_locs = hcat($(p_names.raw)_parent_locs_x, $(p_names.raw)_parent_locs_y)
            
            # 1. Compute intensity on a fine grid
            local intensity_grid = zeros(T, res, res)
            for i in 1:res, j in 1:res
                local intensity_ij = 0.0
                for p_idx in 1:$(n_parents_str)
                    local dist_sq = (grid_x[i] - parent_locs[p_idx, 1])^2 + (grid_y[j] - parent_locs[p_idx, 2])^2
                    local kernel_val = exp(-0.5 * dist_sq / ($(p_names.ls)^2))
                    intensity_ij += $(p_names.amplitude)[p_idx] * kernel_val
                end
                intensity_grid[i, j] = intensity_ij
            end

            # 2. Interpolate intensity at observation locations
            local intensity_at_obs = zeros(T, M.s_N)
            local interp_data = spec_registry[:$(spec.key)].precomputes.interpolation_data
            for obs_i in 1:M.s_N
                local idata = interp_data[obs_i]
                local ix, iy, dx, dy = idata.ix, idata.iy, idata.dx, idata.dy
                
                # Bilinear interpolation
                local c00 = intensity_grid[ix, iy]
                local c10 = intensity_grid[ix+1, iy]
                local c01 = intensity_grid[ix, iy+1]
                local c11 = intensity_grid[ix+1, iy+1]
                
                local c0 = c00 * (1 - dx) + c10 * dx
                local c1 = c01 * (1 - dx) + c11 * dx
                
                intensity_at_obs[obs_i] = c0 * (1 - dy) + c1 * dy
            end
            
            # 3. Evaluate likelihood
            $(likelihood_code)
        end
    """

    if m.method == :direct
        return direct_code
    elseif m.method == :grid
        return grid_code
    else
        error("Unsupported method '$(m.method)' for ShotNoiseCoxProcess.")
    end
end


"""
    get_effects(m::ShotNoiseCoxProcess, chain, M::NamedTuple, ...)

Reconstructs the `ShotNoiseCoxProcess` component's intensity surface from posterior
samples. This function supports both `:direct` and `:grid` methods.
"""
function get_effects(
    m::ShotNoiseCoxProcess, chain, M::NamedTuple, n_samples::Int, outcomes_N::Int,
    spec::NamedTuple, PS::Union{NamedTuple, Nothing}, N_total::Int
)::NamedTuple
    structured_effects = Vector{Matrix{Float64}}()
    
    obs_locs_train = spec.precomputes.obs_locs
    obs_locs_full = if !isnothing(PS) && hasproperty(PS, :centroids)
        vcat(obs_locs_train, PS.centroids)
    else
        obs_locs_train
    end
    n_obs_full = length(obs_locs_full)

    for k in 1:outcomes_N
        p_names = generate_full_variable_names(spec, M.model_arch, k)
        
        ls_samples = get_params_vector(chain, string(p_names.ls), 1)[:, 1]
        
        n_parents_samples = if m.n_parents isa UnivariateDistribution
            get_params_vector(chain, string(p_names.latent), 1)[:, 1]
        else
            fill(Float64(m.n_parents), n_samples)
        end
        max_n_parents = Int(maximum(n_parents_samples))

        parent_locs_x_samples = get_params_vector(chain, string(p_names.raw, "_parent_locs_x"), max_n_parents)
        parent_locs_y_samples = get_params_vector(chain, string(p_names.raw, "_parent_locs_y"), max_n_parents)
        amplitude_samples = get_params_vector(chain, string(p_names.amplitude), max_n_parents)

        effect_k = zeros(Float64, n_obs_full, n_samples)

        for i in 1:n_samples
            current_ls = ls_samples[i]
            current_n_parents = Int(n_parents_samples[i])
            
            current_locs_x = view(parent_locs_x_samples, i, 1:current_n_parents)
            current_locs_y = view(parent_locs_y_samples, i, 1:current_n_parents)
            current_amplitudes = view(amplitude_samples, i, 1:current_n_parents)

            intensity_sample = zeros(n_obs_full)
            for obs_idx in 1:n_obs_full
                intensity_obs = 0.0
                for p_idx in 1:current_n_parents
                    dist_sq = (obs_locs_full[obs_idx].x - current_locs_x[p_idx])^2 + (obs_locs_full[obs_idx].y - current_locs_y[p_idx])^2
                    kernel_val = exp(-0.5 * dist_sq / (current_ls^2))
                    intensity_obs += current_amplitudes[p_idx] * kernel_val
                end
                intensity_sample[obs_idx] = intensity_obs
            end
            effect_k[:, i] = intensity_sample
        end
        push!(structured_effects, effect_k)
    end
    
    return (structured=structured_effects, noisy=structured_effects)
end
