# This file contains the proposed new and updated functions for the bstm refactoring.
 

"""
    ShotNoiseCoxProcess <: ComponentModel

A component model for a Shot Noise Cox Process, used for modeling spatial point patterns.
The intensity surface is generated by placing a number of "parent" points (the "shots")
in the domain, each contributing a kernel-based bump to the overall intensity.

# Fields
- `n_parents::Union{Int, UnivariateDistribution}`: The number of parent points. Can be fixed or a random variable.
- `kernel::String`: The name of the kernel function for each shot (e.g., "se").
- `lengthscale::Distribution`: The prior for the kernel lengthscale.
- `amplitude::Distribution`: The prior for the amplitude (height) of each shot.
"""
struct ShotNoiseCoxProcess <: ComponentModel
    n_parents::Union{Int, UnivariateDistribution}
    kernel::String
    lengthscale::Distribution
    amplitude::Distribution
end

# Add to the central component constructor registry.
COMPONENT_CONSTRUCTORS[:sncp] = (p, params) -> ShotNoiseCoxProcess(
    get(params, :n_parents, 50),
    string(get(params, :kernel, "se")),
    p.lengthscale,
    p.amplitude
)

# Add to the model-to-structure map.
MODEL_TO_STRUCTURE_MAP[ShotNoiseCoxProcess] = :spatial

"""
    get_datastructures!(m_type::Type{<:ShotNoiseCoxProcess}, M::Dict, mod_data::Dict)::Bool

Performs data-dependent setup for the `ShotNoiseCoxProcess`. It ensures that spatial
coordinates are available to define the domain and that grid areas are processed.
It assumes a point process where observations `y` correspond to counts in areal units.
"""
function get_datastructures!(m_type::Type{<:ShotNoiseCoxProcess}, M::Dict, mod_data::Dict)::Bool
    params = mod_data[:params]
    data = M[:data]

    # Ensure spatial coordinates are present to define the domain.
    if !hasproperty(data, :s_x) || !hasproperty(data, :s_y)
        error("ShotNoiseCoxProcess requires continuous spatial coordinates `s_x` and `s_y` to define the domain.")
    end

    # Unlike GMRFs, SNCP works with continuous coordinates, not just indices.
    # We still need to define s_N as the number of observation locations.
    if !haskey(M, :s_N)
        if haskey(M, :s_idx)
            M[:s_N] = length(unique(M[:s_idx]))
        else
            M[:s_N] = nrow(data)
            M[:s_idx] = 1:M[:s_N]
            @warn "Spatial index `s_idx` not found. Assuming one observation per unique location, ordered as in the data."
        end
    end

    # Ensure centroids (observation locations) are available.
    if !haskey(M, :centroids)
        coord_map = Dict{Int, Point2D}()
        for i in 1:nrow(data)
            idx = M[:s_idx][i]
            if !haskey(coord_map, idx)
                coord_map[idx] = Point2D(data.s_x[i], data.s_y[i])
            end
        end
        if length(coord_map) < M[:s_N]
            error("Could not resolve unique coordinates for all $(M[:s_N]) spatial units.")
        end
        M[:centroids] = [coord_map[i] for i in 1:M[:s_N]]
    end

    # Handle grid_areas, which are necessary for the Poisson likelihood.
    if haskey(params, :grid_areas)
        ga_val = params[:grid_areas]
        if ga_val isa Symbol && hasproperty(data, ga_val)
            M[:grid_areas] = data[!, ga_val]
        elseif ga_val isa AbstractVector
            M[:grid_areas] = ga_val
        else
            calling_mod = get(M, :calling_module, Main)
            try; M[:grid_areas] = Core.eval(calling_mod, ga_val);
            catch; @warn "Could not resolve grid_areas for ShotNoiseCoxProcess. Defaulting to unit areas."; M[:grid_areas] = ones(M[:s_N]); end
        end
    else
        @warn "ShotNoiseCoxProcess model specified, but `grid_areas` parameter is missing. Defaulting to unit areas."
        M[:grid_areas] = ones(M[:s_N])
    end

    # Ensure y_obs is a vector of counts, one for each spatial unit.
    if M[:y_obs] isa AbstractMatrix
        if size(M[:y_obs], 2) > 1
            error("ShotNoiseCoxProcess only supports a single outcome variable.")
        end
        M[:y_obs] = vec(M[:y_obs])
    end
    if length(M[:y_obs]) != M[:s_N]
        @warn "Length of y_obs ($(length(M[:y_obs]))) does not match number of spatial units s_N ($(M[:s_N])). Ensure data is aggregated to one count per spatial unit."
    end

    return true
end

"""
    get_precomputes(m::ShotNoiseCoxProcess, M::NamedTuple, mod_data::Dict)::NamedTuple

Performs pre-calculations for the `ShotNoiseCoxProcess`. It determines the spatial
domain bounds from the observation coordinates for placing the parent points.
"""
function get_precomputes(m::ShotNoiseCoxProcess, M::NamedTuple, mod_data::Dict)::NamedTuple
    # Extract domain bounds from the observation coordinates.
    coords = M.data[!, [:s_x, :s_y]]
    x_min, x_max = extrema(coords.s_x)
    y_min, y_max = extrema(coords.s_y)
    
    domain_bounds = (x_min=x_min, x_max=x_max, y_min=y_min, y_max=y_max)

    return (
        domain_bounds = domain_bounds,
        obs_locs = M.centroids,
        grid_areas = M.grid_areas
    )
end

"""
    get_priors(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing}, M::NamedTuple)::String

Generates the Turing code for the `ShotNoiseCoxProcess` component's priors.
"""
function get_priors(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing}, M::NamedTuple)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    bounds = spec.precomputes.domain_bounds

    priors = String[]

    # Prior for the number of parents, if it's a distribution
    n_parents_str = if m.n_parents isa UnivariateDistribution
        push!(priors, "$(p_names.latent) ~ NamedDist($(_distribution_to_string(m.n_parents)), :$(p_names.latent))")
        string(p_names.latent)
    else
        string(m.n_parents)
    end

    # Priors for parent locations, lengthscale, and amplitude
    push!(priors, "$(p_names.raw)_parent_locs_x ~ NamedDist(filldist(Uniform(T($(bounds.x_min)), T($(bounds.x_max))), $(n_parents_str)), :$(Symbol(string(p_names.raw, "_parent_locs_x"))))")
    push!(priors, "$(p_names.raw)_parent_locs_y ~ NamedDist(filldist(Uniform(T($(bounds.y_min)), T($(bounds.y_max))), $(n_parents_str)), :$(Symbol(string(p_names.raw, "_parent_locs_y"))))")
    push!(priors, "$(p_names.ls) ~ NamedDist($(_distribution_to_string(m.lengthscale)), :$(p_names.ls))")
    push!(priors, "$(p_names.amplitude) ~ NamedDist(filldist($(_distribution_to_string(m.amplitude)), $(n_parents_str)), :$(p_names.amplitude))")
    
    return join(priors, "\n    ")
end

"""
    get_updates(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing}, M::NamedTuple)::String

Generates the Turing code to construct the `ShotNoiseCoxProcess` intensity surface
and its custom Poisson likelihood. This component overrides the standard likelihood evaluation.
"""
function get_updates(m::ShotNoiseCoxProcess, spec::NamedTuple, arch::String, outcome_idx::Union{Int, Nothing}, M::NamedTuple)::String
    p_names = generate_full_variable_names(spec, arch, outcome_idx)
    
    n_parents_str = if m.n_parents isa UnivariateDistribution
        string(p_names.latent)
    else
        string(m.n_parents)
    end

    return """
        # --- ShotNoiseCoxProcess Model: $(spec.key) ---
        local obs_locs = spec_registry[:$(spec.key)].precomputes.obs_locs
        local parent_locs = hcat($(p_names.raw)_parent_locs_x, $(p_names.raw)_parent_locs_y)
        
        local intensity_at_obs = zeros(T, M.s_N)
        for i in 1:M.s_N
            local intensity_i = zero(T)
            for j in 1:$(n_parents_str)
                local dist_sq = (obs_locs[i].x - parent_locs[j, 1])^2 + (obs_locs[i].y - parent_locs[j, 2])^2
                local kernel_val = exp(T(-0.5) * dist_sq / ($(p_names.ls)^2))
                intensity_i += $(p_names.amplitude)[j] * kernel_val
            end
            intensity_at_obs[i] = intensity_i
        end

        local grid_areas = spec_registry[:$(spec.key)].precomputes.grid_areas
        for s in 1:M.s_N
            local y_s = M.y_obs[s] 
            local A_s = grid_areas[s]
            local lambda_s = intensity_at_obs[s] * A_s
            
            # Add base contribution from other model components to the log-intensity
            lambda_s *= exp(eta[s])

            Turing.@addlogprob! (y_s * log(lambda_s + T(1e-9)) - lambda_s)
        end
        M[:likelihood_handled] = true # Signal to assembler that likelihood is handled
    """
end

"""
    get_effects(m::ShotNoiseCoxProcess, chain, M::NamedTuple, n_samples::Int, outcomes_N::Int, p_names::NamedTuple, spec::NamedTuple, PS::Union{NamedTuple, Nothing}, N_total::Int)::NamedTuple

Reconstructs the `ShotNoiseCoxProcess` component's intensity surface from posterior samples.
"""
function get_effects(m::ShotNoiseCoxProcess, chain, M::NamedTuple, n_samples::Int, outcomes_N::Int, p_names::NamedTuple, spec::NamedTuple, PS::Union{NamedTuple, Nothing}, N_total::Int)::NamedTuple
    # Extract posterior samples
    ls_samples = get(chain, p_names.ls)
    
    # Handle variable number of parents
    n_parents_samples = if m.n_parents isa UnivariateDistribution
        get(chain, p_names.latent)
    else
        fill(m.n_parents, n_samples)
    end
    max_n_parents = maximum(n_parents_samples)

    # These parameters will have a variable number of columns if n_parents is random
    parent_locs_x_samples = get(chain, Symbol(string(p_names.raw, "_parent_locs_x")))
    parent_locs_y_samples = get(chain, Symbol(string(p_names.raw, "_parent_locs_y")))
    amplitude_samples = get(chain, p_names.amplitude)

    obs_locs = spec.precomputes.obs_locs
    n_obs = length(obs_locs)
    
    reconstructed_intensity = zeros(n_samples, n_obs)

    for i in 1:n_samples
        current_ls = ls_samples[i]
        current_n_parents = n_parents_samples[i]
        
        current_locs_x = parent_locs_x_samples[i, 1:current_n_parents]
        current_locs_y = parent_locs_y_samples[i, 1:current_n_parents]
        current_amplitudes = amplitude_samples[i, 1:current_n_parents]

        intensity_sample = zeros(n_obs)
        for obs_idx in 1:n_obs
            intensity_obs = 0.0
            for p_idx in 1:current_n_parents
                dist_sq = (obs_locs[obs_idx].x - current_locs_x[p_idx])^2 + (obs_locs[obs_idx].y - current_locs_y[p_idx])^2
                kernel_val = exp(-0.5 * dist_sq / (current_ls^2))
                intensity_obs += current_amplitudes[p_idx] * kernel_val
            end
            intensity_sample[obs_idx] = intensity_obs
        end
        reconstructed_intensity[i, :] = intensity_sample
    end

    mean_effect = mean(reconstructed_intensity, dims=1)[:]
    lower_ci = quantile(reconstructed_intensity, 0.025, dims=1)[:]
    upper_ci = quantile(reconstructed_intensity, 0.975, dims=1)[:]

    # This effect is at the spatial unit level, not observation level.
    # The `_modular_eta_assembly` will handle indexing if needed.
    return (structured=(mean=mean_effect, lower=lower_ci, upper=upper_ci),)
end 